In [5]:
!pip install numpy

In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
print(arr)

[1 2 3 4 5]


In [10]:
type(arr)

numpy.ndarray

In [11]:
arr.shape

(5,)

In [13]:
arr.ndim

1

In [14]:
arr2 = arr.reshape(1,5)

In [15]:
arr2

array([[1, 2, 3, 4, 5]])

In [16]:
arr2.shape

(1, 5)

In [17]:
arr2.ndim

2

In [18]:
arr=np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [20]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [21]:
arr = np.arange(1, 12, 2)
arr

array([ 1,  3,  5,  7,  9, 11])

In [22]:
arr.reshape(6,1)

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]])

In [23]:
arr

array([ 1,  3,  5,  7,  9, 11])

In [24]:
ones_arr=np.ones(5)

In [26]:
ones_arr

array([1., 1., 1., 1., 1.])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [34]:
## Attriubutes
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(2, 3)
2
6
int64
8


In [37]:
## Vectorized operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [38]:
## Universal functions
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [42]:
## statistical ops
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std = np.std(data)
normalized_data = (data - mean) / std
print(normalized_data)

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
3.5
1.707825127659933
3.5
2.9166666666666665


In [47]:
#logical operations

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data > 5)
print(data[data>5])
print(data[(data>=5) & (data <= 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
